AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
