default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: document_management_system_development
  password: <%= ENV.fetch('DB_PASS') { '' } %>

test:
  <<: *default
  database: document_management_system_test

production:
  <<: *default
  database: document_management_system_production
  username: document_management_system
  password: <%= ENV['DOCUMENT_MANAGEMENT_SYSTEM_DATABASE_PASSWORD'] %>
